version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
    groups:
      rendering-abi:
        patterns: ['SkiaSharp*', 'HarfBuzzSharp*', 'Uno.*']
    ignore:
      - dependency-name: SkiaSharp*
        update-types: ['version-update:semver-major']
      - dependency-name: HarfBuzzSharp*
        update-types: ['version-update:semver-major']
