namespace LightSpace.Workbench;

public sealed partial class StudioView
{
    private Task ShowHelpAsync()
    {
        var panel = new StackPanel { Spacing = 10 };
        foreach (var (title, body) in new[]
        {
            ("Start with your photographs", "Add photos imports JPEG, PNG, WebP, BMP and GIF. Originals remain unchanged. Camera RAW, DNG, HEIF and TIFF decoding are not included."),
            ("Crop ratios and anchors", "Crop or R offers locked/free presets and custom width/height. Ratios describe final output after quarter turns. Corners keep the opposite anchor; edges keep the opposite edge and perpendicular center. Alt/Option resizes about the center. Shift temporarily locks the current ratio for an unlocked gesture. Policies are captured at pointer-down; bounds remain inside the frame and above the existing one-percent minimum."),
            ("Crop guides and cancellation", "A toggles locking; X swaps width/height without changing flags; arrows nudge one source pixel or ten with Shift. O cycles Thirds, Grid, Golden ratio, Diagonals, Triangle and None; Shift+O reverses Triangle. Enter returns to Edit outside text inputs. Escape cancels capture. Resize/scale/layout changes invalidate the captured frame and cancel an uncommitted crop. Guides and locks are session-local, excluded from exports; numeric crop bounds persist."),
            ("Virtual copies", "Manage virtual copies creates independent alternatives sharing the original source. Create one or a selection, rename, filter Originals/Virtual copies, and Survey the family. Copies point directly to the original and inherit starting metadata/album links. Later edits are independent; named versions start empty."),
            ("Copy removal and undo", "Confirmed removal affects only virtual-copy records and album references, never originals or files. Create/rename/remove are undoable without discarding unrelated imports. Removing an active copy activates a surviving selected photo, or selects its original if none remains. Master promotion and automatic stacks are not implemented."),
            ("Non-destructive development", "Sliders, curves, grading, optics, geometry, crop and masks change settings rather than source bytes. Double-click resets sliders or enter numbers. Each completed gesture is one undo transaction; Escape cancels capture before leaving its tool."),
            ("Survey culling", "Survey or N compares selected photos, falling back to filtered photos when needed. Twelve candidates appear per page. Rating and P/X/U apply to the active candidate only. Exclude/Delete narrows the survey without deleting catalog records. Restore excluded reverses it. Enter/double-click opens Detail. Preparation is one photo per dispatcher tick, not background/GPU decoding."),
            ("Reference and selective settings", "Shift+R pins a session-local look beside active editing with fit-relative linked/independent navigation and side-by-side/stacked layouts. Selective matching, copy and sync offer thirteen groups. Global excludes geometry/crop/masks/clones. Reviewed source/targets are captured and applied in one transaction, retaining metadata. Ctrl/Cmd+C copies all processing; Ctrl/Cmd+Shift+C opens group selection; Ctrl/Cmd+V pastes."),
            ("Optics and geometry", "Manual distortion, lens falloff and radial channel alignment combine with perspective, rotation, aspect, scale and offsets. Constrain crop conservatively fills the frame; it is not calibrated lens correction or automatic/guided Upright. Straighten captures a drawn horizon and commits on release. Mask/picking coordinates remain attached through corrections."),
            ("White balance and histogram", "W samples a neutral source-preview patch for relative Temperature/Tint, not RAW Kelvin calibration. Black/transparent samples are rejected. Drag histogram tone regions to edit; release commits and Escape cancels. Triangles or J toggle clipping indicators, excluded from export and histogram measurements."),
            ("Workspace layout", "Resize panels with their grips. Escape cancels, double-click/Home resets, and focused arrows resize. F6 hides panels/filmstrip for focus; F7 toggles the filmstrip. Layout state is session-local. Editing previews target 2560 pixels; source-pixel zoom cannot recover omitted native-resolution detail."),
            ("Curves and grading", "RGB curves supports master, red, green and blue with up to thirty-two points, numeric/keyboard editing and shape-preserving or linear interpolation. The legacy five-point curve runs first. Grade opens shadows/midtones/highlights/global wheels with luminance, blending and balance; grading follows monochrome."),
            ("Masks and sampled colors", "Drag gradients and their handles. Luminance restricts source brightness. Color range uses click to replace, Shift-click to add five samples and Alt-click/swatches to remove. Oklab tolerance and smoothness refine coverage. Sampling excludes development and overlays. Eight masks are supported."),
            ("Brush and clone", "B selects painting. Size, feather, flow, density and pressure are captured per stroke. Erase subtracts, Alt temporarily erases and brackets change size. Escape cancels. Coverage is capped at 1024 pixels even for export; physical pen hardware is unverified. Clone has thirty-two source stamps, not healing or generative removal. Coverage overlays do not export."),
            ("XMP and output", "Photo information offers reviewed XMP import/export. Metadata-only import preserves processing. Native settings retain the selected look, not copy-family identity. Camera Raw mappings are a limited subset, not Adobe pixel equivalence. JPEG/PNG/WebP output is 8-bit sRGB, capped at 8192 pixels, without source EXIF/IPTC embedding. Copy filenames identify the alternative."),
            ("Recovery and compatibility", "Saved acknowledges committed completed writes, not previews. Click to flush/retry; damaged recovery stays protected until explicit replacement. Catalog schema 6, native XMP 5, manifest 1 and IndexedDB 2 are unchanged. Crop bounds persist, lock/guides do not. Reload to update without clearing site data. Keep pre-upgrade portable backups for older builds."),
            ("Storage and privacy", "Recovery stores originals by SHA-256 and commits separate metadata. Warm metadata/copy changes reuse stored originals without rehashing or rewriting source bytes. Restore validates source integrity and family relationships. Orphans are retained; there is no encryption, cross-tab merge or crash journal. Retain source files and portable backups. No account, photo upload or cloud processing is used."),
            ("About LightSpace", "Independent MIT-licensed Uno software, not an Adobe product or complete Lightroom parity. Composed Skia effects can execute on GPU-backed hosts. Distinct visible looks still shade separately; decoding, histogram and export retain CPU work. No separate WebGPU engine, RAW/AI, calibrated profiles, HDR/panorama, native-resolution tiling, printing or cloud workflows are included.")
        })
        { panel.Children.Add(Theme.Text(title, 13)); panel.Children.Add(Note(body)); }
        ShowDialog("LightSpace guide", panel, "Close", () => Task.CompletedTask);
        return Task.CompletedTask;
    }
}
