namespace LightSpace.Workbench;

public sealed partial class StudioView
{
    private Task ShowHelpAsync()
    {
        var panel = new StackPanel { Spacing = 10 };
        foreach (var (title, body) in new[]
        {
            ("Start with your photographs", "Add photos imports JPEG, PNG, WebP, BMP and GIF. Originals remain unchanged. Camera RAW, DNG, HEIF and TIFF decoding are not included."),
            ("Virtual copies", "Manage virtual copies on the right rail creates independent alternative looks sharing the original source. Create one or copies for the selection, rename them, filter Originals/Virtual copies, and Survey the family. A copy of a copy still references the original directly. Copies inherit album membership and starting metadata; later processing and metadata edits remain independent. Named versions start empty on each new copy."),
            ("Copy removal and undo", "Remove this copy requires confirmation and removes only a virtual-copy record and its album references, never the original or its source file. Creation, rename and removal are undoable. Undo restores the same identity and appearance without discarding unrelated imports. Set Copy As Master and automatic stacks are not implemented. Portable backups preserve families and store source bytes once per original."),
            ("Non-destructive development", "Sliders, curves, grading, optics, geometry, crop and masks change settings rather than source bytes. Double-click a slider to reset it or enter a number. Each completed gesture is one undo transaction; Escape cancels a captured gesture before leaving its tool."),
            ("Survey culling", "Survey view or N compares selected photos, or filtered photos when fewer than two are selected. Twelve previews fit each page. Click a candidate; 0–5 rates only that photo, P/X/U sets flags, arrows and Page Up/Down navigate. The cross or Delete excludes from this survey only, never deleting catalog records or originals. Restore excluded restores the group. Enter/double-click opens Detail. Preparation is one photo per dispatcher tick with a bounded cache, not background or GPU decoding."),
            ("Reference comparison", "Reference view or Shift+R pins the current look beside active editing. Edit or choose another filmstrip photograph while the reference stays frozen. The header can pin again, fit both, link navigation, switch side-by-side/stacked, apply selected reference settings, or close. Linking is fit-relative, not registered image alignment. Reference state is session-only, unlike a persistent virtual copy."),
            ("Selective settings", "Copy settings and Synchronize settings open thirteen processing groups. Global excludes geometry, crop, masks and clones. Paste applies only captured groups; metadata and unselected edits remain intact. Synchronization captures its source/targets before review and commits one undoable transaction. Ctrl/Cmd+C copies all processing; Ctrl/Cmd+Shift+C selects groups; Ctrl/Cmd+V pastes. Control-click selects synchronization targets."),
            ("Optics and geometry", "Optics supplies manual distortion, lens falloff and radial red/cyan or blue/yellow alignment. Geometry adds vertical/horizontal perspective, rotation, aspect, scale and offsets. Constrain crop conservatively enlarges the image to fill the frame. These are original manual models, not calibrated lens profiles or automatic Adobe Upright."),
            ("Crop and straighten", "Crop has free handles, centered ratios, quarter turns and flips. Straighten lets you drag a horizon and commits on release; Escape restores the opening angle. Done returns to Edit. Ratios are presets, not a continuous aspect lock. Mask and sampled-color positions remain attached to the source through corrections."),
            ("White balance", "White balance picker or W samples a neutral source-preview patch to estimate relative Temperature and Tint. Black/transparent areas are rejected and correction limits are reported. This is not camera Kelvin or RAW calibration."),
            ("Histogram and clipping", "Drag Blacks, Shadows, Exposure, Highlights or Whites regions in the histogram. Release commits once; Escape cancels. Corner triangles toggle clipping independently; J toggles both. Blue shadows and red highlights are display-only and excluded from export and histogram measurements."),
            ("Workspace layout", "Drag library/edit-panel dividers to resize. Escape cancels, double-click/Home resets, and focused arrows resize. F6/Focus hides panels and filmstrip; F7 toggles the filmstrip. Layout changes do not edit photos and remain session-local."),
            ("RGB point curves", "RGB curves opens master, red, green and blue curves. Add/drag points or enter Input/Output values. Delete removes an interior point. Smooth is shape-preserving; Linear uses straight segments. Up to 32 points per channel are supported; the legacy five-point curve runs first."),
            ("Four-way grading", "Grade opens shadows, midtones, highlights and global wheels. Drag hue/saturation or use numeric controls. Luminance, blending and balance refine the result. Grading follows monochrome and participates in copied settings, versions and export."),
            ("Masks and sampled colors", "Drag gradients and their center, radius, fade or rotation handles. Luminance restricts source brightness. Color range uses click to replace, Shift-click to add up to five samples, and Alt-click or swatches to remove. Oklab tolerance/smoothness refine coverage. Samples come from source pixels, not development or the overlay."),
            ("Brush masks", "Brush or B paints; Paint selected modifies an existing mask. Size, feather, flow and density are captured per stroke. Erase subtracts; Alt temporarily erases; brackets change size. Each stroke is undoable and Escape cancels. Coverage is capped at 1024 pixels even for export. Physical pen hardware is not certified by CI."),
            ("Coverage and clone", "Coverage displays the selected mask in red and never enters exported images or histogram samples. Clone uses Alt-click for a source and click for a destination, with 32 feathered stamps. It is not healing or generative removal."),
            ("Organize and compare", "Grid/filmstrip and Control-click select photographs. Ratings, flags, captions and keywords support filters; albums reference originals. The before/after divider retains optical/geometric alignment. Previews target 2560 pixels; source-pixel zoom cannot recover absent native-resolution detail."),
            ("XMP sidecars", "Photo information supplies Import/Export XMP. Review supported fields and warnings before Apply. Metadata only preserves processing; the native extension retains complete selected-look settings, not virtual-copy family identity. Camera Raw mappings are a limited scalar/curve subset, not Adobe pixel equivalence. Unknown properties are not retained."),
            ("Keyboard", "G: grid · E/D: edit · N: Survey · R: crop · Shift+R: reference · M: masks · B: brush · W: white balance · J: clipping · F6: focus · F7: filmstrip · Z: zoom · Y: compare · backslash: original · 0–5: rating · P/X/U: flags · Ctrl/Cmd+Z: undo · Ctrl/Cmd+Shift+Z: redo · Ctrl/Cmd+I: import · Ctrl/Cmd+S: catalog backup. Focused controls use their own editing keys."),
            ("Recovery and compatibility", "Saved acknowledges completed committed revisions, not previews. Click to save/retry. Unreadable recovery stays protected until explicit replacement. Catalog schema 6 adds copy families and migrates versions 1–5. Native XMP settings remain 5; recovery manifest/IndexedDB remain 1/2. Older builds reject schema 6: keep pre-upgrade portable backups. Reload to update; do not clear site data."),
            ("Incremental storage", "Recovery stores originals by SHA-256 and publishes edit metadata. Warm copy creation/rename reuses its stored source without rehashing or rewriting original bytes. Startup validates source length/hash and family references. Portable catalogs store each family's bytes once. Orphan sources remain retained; no encrypted vault, cross-tab merge or crash journal is included."),
            ("Export and privacy", "JPEG/PNG/WebP exports are 8-bit sRGB with an 8192-pixel cap and no embedded source EXIF/IPTC. Copy filenames identify the selected alternative. Recovery is local and unencrypted. Retain source files and portable backups. No account, photo upload or cloud processing is used."),
            ("About LightSpace", "Independent MIT-licensed Uno software, not an Adobe product or complete Lightroom parity. Composed Skia effects can run on GPU-backed hosts; matching copy/reference sources share decoding within their renderer. Distinct visible looks still add shading work. No separate WebGPU engine is included; decode, histogram and export retain CPU work. RAW/AI, calibrated profiles, HDR/panorama, native-resolution tiling, printing and cloud workflows remain unimplemented.")
        })
        { panel.Children.Add(Theme.Text(title, 13)); panel.Children.Add(Note(body)); }
        ShowDialog("LightSpace guide", panel, "Close", () => Task.CompletedTask);
        return Task.CompletedTask;
    }
}
