namespace LightSpace.Workbench;

public sealed partial class StudioView
{
    private Task ShowHelpAsync()
    {
        var panel = new StackPanel { Spacing = 10 };
        foreach (var (title, body) in new[]
        {
            ("Start with your photographs", "Add photos imports JPEG, PNG, WebP, BMP and GIF. Originals remain unchanged. Camera RAW, DNG, HEIF and TIFF decoding are not included."),
            ("Non-destructive development", "Sliders, curves, grading, optics, geometry, crop and masks change settings rather than source bytes. Double-click a slider to reset it or enter a number. Each completed gesture is one undo transaction; Escape cancels a captured gesture before leaving its tool."),
            ("Survey culling", "Survey view or N compares selected photos, or filtered photos when fewer than two are selected. Twelve previews fit each page. Click a candidate; 0–5 rates only that photo, P/X/U sets flags, arrows and Page Up/Down navigate. The cross or Delete excludes from this survey only, never deleting catalog photos or originals. Restore excluded restores the group. Enter/double-click opens Detail. Preparation is one photo per dispatcher tick with a separate bounded cache; it is not background or GPU decoding."),
            ("Reference comparison", "Reference view or Shift+R pins the current edited look beside the active photo. Edit the active photo or choose another filmstrip photo while the reference stays frozen. The header can pin again, fit both, link navigation, switch side-by-side/stacked layout, apply selected reference settings, or close. Linking uses fit-relative zoom and viewport-relative pan, not registered image alignment. Reference state is session-only, adds no catalog photo, and clears when the catalog is replaced or the app reloads."),
            ("Selective settings", "Copy settings and Synchronize settings open thirteen independently selectable processing groups. Global excludes geometry, crop, masks and clone spots. Paste applies only the copied groups; metadata and unselected edits are retained. Synchronization captures the active source and the other selected targets before review and applies one undoable transaction. Ctrl/Cmd+C copies all processing; Ctrl/Cmd+Shift+C opens group selection; Ctrl/Cmd+V pastes. Control-click selects synchronization targets."),
            ("Optics and geometry", "Optics supplies manual distortion, lens falloff and radial red/cyan or blue/yellow alignment. Geometry adds vertical/horizontal perspective, rotation, aspect, scale and offsets. Constrain crop conservatively enlarges the image to keep the frame filled. These are original manual models, not calibrated lens profiles or automatic Adobe Upright."),
            ("Crop and straighten", "Crop has free handles, centered ratio presets, quarter turns and flips. Straighten lets you drag a horizon line and commits its angle on release; Escape restores the opening angle. Done returns to Edit. Ratio presets are not a continuous aspect lock. Mask and sampled-color positions remain attached to the source through corrections."),
            ("White balance", "Use the White balance picker or W, then click a neutral patch. A bounded source-preview sample estimates relative Temperature and Tint. Black/transparent areas are rejected and correction limits are reported. This is not camera Kelvin or RAW white-balance calibration."),
            ("Histogram and clipping", "Drag the histogram's Blacks, Shadows, Exposure, Highlights or Whites region to adjust that tone. Release commits once; Escape cancels. Corner triangles toggle clipping independently and J toggles both. Blue shadows and red highlights are display-only indicators, excluded from exports and histogram measurements."),
            ("Workspace layout", "Drag the library or edit-panel divider to resize it. Escape cancels, double-click/Home resets, and focused arrows resize. F6 or Focus mode hides side panels and filmstrip; F7 toggles the filmstrip. Layout changes do not edit the photo and are kept for the current workbench session."),
            ("RGB point curves", "RGB curves opens master, red, green and blue curves. Click to add points, drag them, or enter Input/Output values. Delete removes an interior point. Smooth uses shape-preserving interpolation; Linear uses straight segments. Up to 32 points per channel are supported; the legacy five-point curve is applied first."),
            ("Four-way grading", "Grade opens shadows, midtones, highlights and global wheels. Drag hue/saturation or use numeric values; luminance, blending and balance refine the result. Grading follows monochrome conversion and is preserved in copied settings, versions and export."),
            ("Masks and sampled colors", "Drag radial/linear gradients and their center, radius, fade or rotation handles. Luminance restricts source brightness. Color range uses click to replace, Shift-click to add up to five samples, and Alt-click to remove a pin. Oklab tolerance and smoothness refine coverage. Sampling reads source pixels, not the developed image or red overlay."),
            ("Brush masks", "Brush or B selects painting; Paint selected modifies an existing mask. Size, feather, flow and density are captured per stroke. Erase subtracts coverage, Alt temporarily erases, and brackets change size. Each stroke is undoable and Escape cancels. Coverage is capped at 1024 pixels even for export; physical pen hardware is not certified by CI."),
            ("Coverage and clone", "Coverage displays the selected mask in red and never enters exported pixels or histogram samples. Clone uses Alt-click for a source and click for a destination, with up to 32 feathered stamps. It is not healing or generative removal."),
            ("Organize and compare", "Grid/filmstrip and Control-click support selection. Ratings, flags, captions and keywords support filtering; albums reference originals. Drag the before/after divider without creating an edit. Comparison retains optical/geometric alignment. Previews are capped at 2560 pixels, so source-pixel zoom cannot recover absent native-resolution detail."),
            ("XMP sidecars", "Photo information supplies Import XMP and Export XMP. Review supported fields and warnings before Apply. Metadata only preserves processing; a native extension retains complete LightSpace settings. Camera Raw mappings are a limited scalar/curve subset, not equivalent Adobe processing. Unknown third-party properties are not retained on re-export."),
            ("Keyboard", "G: grid · E/D: edit · R: crop · Shift+R: reference · M: masks · B: brush · W: white balance · J: clipping · F6: focus · F7: filmstrip · Z: zoom · Y: compare · backslash: original · 0–5: rating · P/X/U: flags · Ctrl/Cmd+Z: undo · Ctrl/Cmd+Shift+Z: redo · Ctrl/Cmd+I: import · Ctrl/Cmd+S: catalog backup. Focused controls use their own editing keys."),
            ("Recovery and compatibility", "Saved acknowledges completed committed revisions, never an active preview. Click to save or retry. Unreadable recovery stays protected until explicit replacement. Schema 5 stores optics and geometry; catalogs 1–4 migrate with neutral defaults. Older builds reject new files rather than dropping corrections. IndexedDB remains version 2; no site-data reset is needed."),
            ("Incremental storage", "Recovery stores originals by SHA-256 and publishes a separate edit manifest. Warm metadata saves do not rewrite or rehash unchanged sources. Startup checks source length and hash. Portable catalogs retain original bytes. Unreferenced sources are retained; there is no encrypted vault, cross-tab merge or crash journal."),
            ("Export and privacy", "JPEG/PNG/WebP exports are 8-bit sRGB with an 8192-pixel long-edge cap; source EXIF/IPTC is not embedded. Recovery is local and unencrypted. Keep source files and portable backups. No account, photo upload or cloud processing is used."),
            ("About LightSpace", "Independent MIT-licensed Uno software, not an Adobe product or complete Lightroom parity. Composed Skia shaders can run on a GPU-backed host; both comparison panes draw without an intermediate CPU screenshot and share matching source decodes. There is no separate WebGPU engine. Decode, histogram and export still include CPU work. RAW/AI, calibrated profiles, HDR/panorama, native-resolution tiling, printing and cloud workflows remain unimplemented.")
        })
        { panel.Children.Add(Theme.Text(title, 13)); panel.Children.Add(Note(body)); }
        ShowDialog("LightSpace guide", panel, "Close", () => Task.CompletedTask);
        return Task.CompletedTask;
    }
}
